name: kidsacademybangla
description: "Play, Learn, and Grow in Bangla"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.0.3
  go_router: ^17.0.1
  audioplayers: ^6.5.1
  google_fonts: ^8.2.1
  flutter_staggered_grid_view: ^0.7.0
  http: ^1.3.0
  google_mobile_ads: ^7.0.0
  shared_preferences: ^2.5.4
  youtube_player_flutter: ^9.1.3
  flutter_cache_manager: ^3.4.1
  path_provider: ^2.1.5
  flutter_tts: ^3.7.0
  country_flags: ^3.0.1
  sensors_plus: ^7.1.1
  url_launcher: ^6.3.3
  in_app_update: ^5.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "ic_launcher"
  image_path: "assets/images/logo_no_text.png"
  web:
    generate: true
    image_path: "assets/images/logo_no_text.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/categories/
    - assets/images/animals/
    - assets/images/birds/
    - assets/images/fruits/
    - assets/images/flowers/
    - assets/images/fish/
    - assets/images/electronics/
    - assets/images/body_parts/
    - assets/images/vegetables/
    - assets/images/vehicles/
    - assets/images/dress/
    - assets/images/rhymes/
    - assets/images/solar_system/
    #
    - assets/sounds/
    - assets/sounds/animals/
    - assets/sounds/fruits/
    - assets/sounds/colors/
    - assets/sounds/bangla_vowels/
    - assets/sounds/bangla_consonants/
    - assets/sounds/bangla_numbers/
    - assets/sounds/english_alphabets/
    - assets/sounds/english_numbers/
    - assets/sounds/arabic_alphabets/
    - assets/sounds/arabic_numbers/
    - assets/sounds/english_rhymes/
    - assets/sounds/bangla_rhymes/

  fonts:
    - family: SolaimanLipi
      fonts:
        - asset: assets/fonts/SolaimanLipi.ttf
        - asset: assets/fonts/SolaimanLipi-Bold.ttf
          weight: 700
          
